version: "3.0"
services:
  redis:
    image: "redis:alpine"
    # The Command will make redis-server run with our custom Configuration
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data #Used for persisting data
      - ./redis/conf:/usr/local/etc/redis #Used for configuring redis
    networks:
      - data_sharing
  publisher:
    ports:
      - "3001:80"
    # Makes the compose- build our Image based on the files in publisher folder
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on: 
      - redis
    networks:
      data_sharing:
        aliases:
          - publisher
  publisher2:
    # Makes the compose- build our Image based on the files in publisher folder
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on: 
      - redis
    networks:
      - data_sharing
  subscriber:
      build:
        context: ./subscriber
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on: 
        - redis
        - publisher
      networks:
        - data_sharing
  subscriber2:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - redis
      - publisher
    networks:
      - data_sharing

networks:
  data_sharing:
    driver: bridge